import type { WeatherCondition, WeatherConditionId } from '../types';

export const WEATHER_CONDITIONS: Record<WeatherConditionId, WeatherCondition> =
  {
    sunny: {
      id: 'sunny',
      label: 'Sunny',
      tempMin: 12,
      tempMax: 18,
      iconName: 'Sun',
      iconColor: 'text-yellow-400',
      precipitationChance: 0.05,
    },
    hot_sunny: {
      id: 'hot_sunny',
      label: 'Hot & Sunny',
      tempMin: 25,
      tempMax: 32,
      iconName: 'Sun',
      iconColor: 'text-orange-400',
      precipitationChance: 0.02,
    },
    partly_cloudy: {
      id: 'partly_cloudy',
      label: 'Partly Cloudy',
      tempMin: 14,
      tempMax: 20,
      iconName: 'Cloud',
      iconColor: 'text-zinc-300',
      precipitationChance: 0.15,
    },
    cloudy: {
      id: 'cloudy',
      label: 'Cloudy',
      tempMin: 10,
      tempMax: 16,
      iconName: 'Cloud',
      iconColor: 'text-zinc-400',
      precipitationChance: 0.25,
    },
    overcast: {
      id: 'overcast',
      label: 'Overcast',
      tempMin: 8,
      tempMax: 14,
      iconName: 'Cloud',
      iconColor: 'text-zinc-500',
      precipitationChance: 0.35,
    },
    light_rain: {
      id: 'light_rain',
      label: 'Light Rain',
      tempMin: 8,
      tempMax: 14,
      iconName: 'CloudRain',
      iconColor: 'text-blue-400',
      precipitationChance: 0.7,
    },
    rainy: {
      id: 'rainy',
      label: 'Rainy',
      tempMin: 6,
      tempMax: 12,
      iconName: 'CloudRain',
      iconColor: 'text-blue-500',
      precipitationChance: 0.9,
    },
    windy: {
      id: 'windy',
      label: 'Windy',
      tempMin: 9,
      tempMax: 14,
      iconName: 'Wind',
      iconColor: 'text-zinc-300',
      precipitationChance: 0.2,
    },
    snowy: {
      id: 'snowy',
      label: 'Snowy',
      tempMin: -2,
      tempMax: 3,
      iconName: 'CloudSnow',
      iconColor: 'text-blue-300',
      precipitationChance: 0.8,
    },
    freezing: {
      id: 'freezing',
      label: 'Freezing',
      tempMin: -5,
      tempMax: 0,
      iconName: 'Snowflake',
      iconColor: 'text-blue-200',
      precipitationChance: 0.5,
    },
  };
